# Generated by Django 5.1.7 on 2025-07-25 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Organizer Name"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Organizer Address"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Event Title")),
                ("description", models.TextField(verbose_name="Event Description")),
                ("start_date", models.DateTimeField(verbose_name="Event Date")),
                ("end_date", models.DateTimeField(verbose_name="Event End Date")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Event Location"),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.organizer",
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("VIP", "VIP"), ("REG", "Regular")],
                        default="REG",
                        max_length=50,
                        verbose_name="Ticket Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ticket Price"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(verbose_name="Available Quantity"),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_date"], name="event_start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["end_date"], name="event_end_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("title", "start_date"), name="unique_event_title_start_date"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["event", "ticket_type"], name="ticket_event_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["price"], name="ticket_price_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["available_quantity"], name="ticket_quantity_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_quantity__gte", 0)),
                name="available_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("event", "ticket_type"), name="unique_event_ticket_type"
            ),
        ),
    ]
