# Generated by Django 5.1.7 on 2025-07-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_event_ticket_type",
        ),
    ]
